# Generated by Django 3.0.5 on 2020-11-29 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinepepe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='uuid',
            field=models.UUIDField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='uuid',
            field=models.UUIDField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cinepepe.Director'),
        ),
    ]
