# Generated by Django 3.0.5 on 2020-11-29 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinepepe', '0003_auto_20201129_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='genre',
            new_name='generos',
        ),
    ]
