# Generated by Django 3.0.5 on 2020-11-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinepepe', '0004_auto_20201129_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
