# Generated by Django 3.0.5 on 2020-11-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinepepe', '0005_pelicula_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='generos',
            field=models.ManyToManyField(blank=True, to='cinepepe.Genre'),
        ),
    ]
