# Generated by Django 3.0.5 on 2020-11-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinepepe', '0006_auto_20201129_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='uuid',
            field=models.UUIDField(default='efb6f25b-adbd-4402-8a95-392f327b9d53'),
            preserve_default=False,
        ),
    ]
