# Generated by Django 3.1.2 on 2020-11-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinstance',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='ReleaseDate'),
        ),
    ]
