# Generated by Django 3.1.2 on 2020-11-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20201101_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviestatus',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Proximamente'), ('c', 'En Cartelera'), ('o', 'Out')], default='p', help_text='State of the movie', max_length=1),
        ),
    ]
